import {
  ArrowLeftRight,
  Banknote,
  Briefcase,
  Building2,
  Bus,
  Car,
  CircleEllipsis,
  Clapperboard,
  CreditCard,
  Dumbbell,
  Fuel,
  Gift,
  GraduationCap,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  LineChart,
  PartyPopper,
  PiggyBank,
  Plane,
  Receipt,
  Repeat,
  Shield,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Sparkles,
  Target,
  TrendingUp,
  Users,
  UtensilsCrossed,
  Wallet,
  type LucideIcon,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  utensils: UtensilsCrossed,
  basket: ShoppingBasket,
  bus: Bus,
  fuel: Fuel,
  bag: ShoppingBag,
  receipt: Receipt,
  home: House,
  film: Clapperboard,
  heart: HeartPulse,
  graduation: GraduationCap,
  plane: Plane,
  dumbbell: Dumbbell,
  repeat: Repeat,
  shield: Shield,
  trending: TrendingUp,
  sparkles: Sparkles,
  users: Users,
  circle: CircleEllipsis,
  briefcase: Briefcase,
  laptop: Laptop,
  building: Building2,
  chart: LineChart,
  gift: Gift,
  party: PartyPopper,
  wallet: Wallet,
  bank: Landmark,
  card: CreditCard,
  phone: Smartphone,
  savings: PiggyBank,
  cash: Banknote,
  transfer: ArrowLeftRight,
  target: Target,
  car: Car,
};

export const ICON_OPTIONS = Object.keys(ICONS);

export function Icon({ name, size = 18 }: { name: string; size?: number }) {
  const Component = ICONS[name] ?? CircleEllipsis;
  return <Component size={size} strokeWidth={1.75} aria-hidden="true" />;
}
